/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;

/**
 *
 * @author alumno
 */
public class AddProductJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddProductJDialog.class.getName());

    /**
     * Creates new form AddProductJDialog
     */
    public AddProductJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStylesButton();
    }

    public AddProductJDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStylesButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        productsPanel = new javax.swing.JPanel();
        SupplierLabel = new javax.swing.JLabel();
        supplier1ComboBox = new javax.swing.JComboBox<>();
        ProductLabel = new javax.swing.JLabel();
        productsComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        stock1Spinner = new javax.swing.JSpinner();
        cancel1Button = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        newProductPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        supplier2Label = new javax.swing.JLabel();
        supplier2ComboBox = new javax.swing.JComboBox<>();
        nameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();
        stock2Label = new javax.swing.JLabel();
        stock2Spinner = new javax.swing.JSpinner();
        cancelButton = new javax.swing.JButton();
        save2Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        productsPanel.setBackground(new java.awt.Color(255, 255, 255));

        SupplierLabel.setText("Supplier: ");

        ProductLabel.setText("Product:");

        jLabel1.setText("Stock:");

        stock1Spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cancel1Button.setText("Cancel");

        saveButton.setText("Save");

        javax.swing.GroupLayout productsPanelLayout = new javax.swing.GroupLayout(productsPanel);
        productsPanel.setLayout(productsPanelLayout);
        productsPanelLayout.setHorizontalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productsPanelLayout.createSequentialGroup()
                        .addComponent(SupplierLabel)
                        .addGap(18, 18, 18)
                        .addComponent(supplier1ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productsPanelLayout.createSequentialGroup()
                        .addComponent(ProductLabel)
                        .addGap(18, 18, 18)
                        .addComponent(productsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(stock1Spinner))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productsPanelLayout.createSequentialGroup()
                        .addGap(0, 226, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancel1Button)))
                .addContainerGap())
        );
        productsPanelLayout.setVerticalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierLabel)
                    .addComponent(supplier1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductLabel)
                    .addComponent(productsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stock1Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel1Button)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add product", productsPanel);

        newProductPanel.setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setText("Name:");

        supplier2Label.setText("Supplier:");

        nameTextField.setText("");

        jLabel4.setText("Price:");

        priceSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 50.0d));

        stock2Label.setText("Stock:");

        cancelButton.setText("Cancel");

        save2Button.setText("Save");

        javax.swing.GroupLayout newProductPanelLayout = new javax.swing.GroupLayout(newProductPanel);
        newProductPanel.setLayout(newProductPanelLayout);
        newProductPanelLayout.setHorizontalGroup(
            newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newProductPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextField))
                    .addGroup(newProductPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(priceSpinner))
                    .addGroup(newProductPanelLayout.createSequentialGroup()
                        .addComponent(supplier2Label)
                        .addGap(18, 18, 18)
                        .addComponent(supplier2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(newProductPanelLayout.createSequentialGroup()
                        .addComponent(stock2Label)
                        .addGap(18, 18, 18)
                        .addComponent(stock2Spinner))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProductPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(save2Button)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        newProductPanelLayout.setVerticalGroup(
            newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProductPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplier2Label)
                    .addComponent(supplier2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stock2Label)
                    .addComponent(stock2Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(save2Button))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add new product", newProductPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void applyStylesButton() {
        cancel1Button.setBackground(new Color(231, 76, 60));
        cancel1Button.setForeground(Color.WHITE);
        cancel1Button.setFont(new Font("Segoe UI", Font.BOLD, 12));
        cancel1Button.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancel1Button.setFocusPainted(false);
        cancel1Button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        cancelButton.setBackground(new Color(231, 76, 60));
        cancelButton.setForeground(Color.WHITE);
        cancelButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        cancelButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelButton.setFocusPainted(false);
        cancelButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        saveButton.setBackground(new Color(0, 191, 255));
        saveButton.setForeground(Color.WHITE);
        saveButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        saveButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        saveButton.setFocusPainted(false);
        saveButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        save2Button.setBackground(new Color(0, 191, 255));
        save2Button.setForeground(Color.WHITE);
        save2Button.setFont(new Font("Segoe UI", Font.BOLD, 12));
        save2Button.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        save2Button.setFocusPainted(false);
        save2Button.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    public void addSelectionComboBoxSupplier(String value){
        this.supplier1ComboBox.addItem(value);
        this.supplier2ComboBox.addItem(value);
    }
    public void addSelectionComboBoxProducts(String value){
        this.productsComboBox.addItem(value);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProductLabel;
    private javax.swing.JLabel SupplierLabel;
    private javax.swing.JButton cancel1Button;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel newProductPanel;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JComboBox<String> productsComboBox;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JButton save2Button;
    private javax.swing.JButton saveButton;
    private javax.swing.JSpinner stock1Spinner;
    private javax.swing.JLabel stock2Label;
    private javax.swing.JSpinner stock2Spinner;
    private javax.swing.JComboBox<String> supplier1ComboBox;
    private javax.swing.JComboBox<String> supplier2ComboBox;
    private javax.swing.JLabel supplier2Label;
    // End of variables declaration//GEN-END:variables
}
