/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author invitado
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        applyStylesButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageJLabel = new javax.swing.JLabel();
        loginJButton = new javax.swing.JButton();
        startJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginJButton.setText("Iniciar Sesión");

        startJButton.setText("Empezar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startJButton)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTamanhoImage(int width, int height) {
        imageJLabel.setSize(width, height);
    }
    
    public void getImagetoLabel(ImageIcon image) {
        int width = imageJLabel.getWidth();
        int height = imageJLabel.getHeight();
        
        Image newImage = image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        
        imageJLabel.setIcon(new ImageIcon(newImage));
    }
    
    private void applyStylesButton() {

        //Estilos para el botón del login
        loginJButton.setBackground(new Color(52, 152, 219));
        loginJButton.setForeground(Color.WHITE);
        loginJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        loginJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        loginJButton.setFocusPainted(false);
        loginJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        //Estilos para el botón de start
        startJButton.setBackground(new Color(52, 152, 219));
        startJButton.setForeground(Color.WHITE);
        startJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        startJButton.setBorder(BorderFactory.createEmptyBorder(8,15,8,15));
        startJButton.setFocusPainted(false);
        startJButton.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
    }
    
    public void addLoginJButtonActionListener(ActionListener al) {
        this.loginJButton.addActionListener(al);
    }
    
    public void addStartJButtonActionListener(ActionListener al) {
        this.startJButton.addActionListener(al);
    }
    
    public void setVisibleStartJButton(boolean visible) {
        this.startJButton.setVisible(visible);
    }
    
    public void setVisibleLoginJButton(boolean visible) {
        this.loginJButton.setVisible(visible);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JButton loginJButton;
    private javax.swing.JButton startJButton;
    // End of variables declaration//GEN-END:variables
}
