/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author alumno
 */
public class RegistrarseJDialog extends javax.swing.JDialog {
    

    /**
     * Creates new form RegistrarseJDialog
     */
    public RegistrarseJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittleJLabel = new javax.swing.JLabel();
        dniJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        phoneJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        DNIJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();
        phoneJTextField = new javax.swing.JTextField();
        passwordJField = new javax.swing.JPasswordField();
        saveJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        creditLabel = new javax.swing.JLabel();
        creditSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tittleJLabel.setText("Registro");

        dniJLabel.setText("DNI:");

        emailJLabel.setText("Correo:");

        nameJLabel.setText("Nome:");

        phoneJLabel.setText("Teléfono:");

        passwordJLabel.setText("Contraseña:");

        saveJButton.setText("Guardar");

        cancelJButton.setText("Cancelar");

        creditLabel.setText("Saldo:");

        creditSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 50.0d));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tittleJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dniJLabel)
                                    .addComponent(nameJLabel)
                                    .addComponent(emailJLabel)
                                    .addComponent(phoneJLabel)
                                    .addComponent(passwordJLabel)
                                    .addComponent(creditLabel))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DNIJTextField)
                                    .addComponent(nameJTextField)
                                    .addComponent(emailJTextField)
                                    .addComponent(phoneJTextField)
                                    .addComponent(passwordJField, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(creditSpinner))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tittleJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DNIJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dniJLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJLabel)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJLabel)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneJLabel)
                    .addComponent(phoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordJLabel)
                    .addComponent(passwordJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditLabel)
                    .addComponent(creditSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveJButton)
                    .addComponent(cancelJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addSaveJButtonActionListener(ActionListener al){
        this.saveJButton.addActionListener(al);
    }   
    
    public void addCancelJButtonActionListener(ActionListener al){
        this.cancelJButton.addActionListener(al);
    }
    
    public void setNameJTextField(String name){
        this.nameJTextField.setText(name);
    }
    
    public String getNameJTextField(){
        return this.nameJTextField.getText();
    }
    
    public String getDNIJTextField(){
        return this.DNIJTextField.getText();
    }
    
    public String getEmailJTextField(){
        return this.emailJTextField.getText();
    }
    
    public String getTelefonoJTextField(){
        return this.phoneJTextField.getText();
    }
    
    public String getPasswordJField(){
        return new String(this.passwordJField.getPassword());
    }
    
    public double getSpinnerValue(){
        return (double) this.creditSpinner.getModel().getValue();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNIJTextField;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel creditLabel;
    private javax.swing.JSpinner creditSpinner;
    private javax.swing.JLabel dniJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JPasswordField passwordJField;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JLabel phoneJLabel;
    private javax.swing.JTextField phoneJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel tittleJLabel;
    // End of variables declaration//GEN-END:variables
}
